---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
 name: fleet-secret
 namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-datasource
    kind: ClusterSecretStore
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  target:
    deletionPolicy: {{ .Values.externalSecrets.deletionPolicy }}
  data:
    - secretKey: {{ .Values.externalSecrets.externalDbPass.name }}
      remoteRef:
        key: {{ .Values.externalSecrets.externalDbPass.path }}
        property: {{ .Values.externalSecrets.externalDbPass.property }}
    - secretKey: {{ .Values.externalSecrets.externalDbHost.name }}
      remoteRef:
        key: {{ .Values.externalSecrets.externalDbHost.path }}
        property: {{ .Values.externalSecrets.externalDbHost.property }}
    - secretKey:  {{ .Values.externalSecrets.externalDbPort.name }}
      remoteRef:
        key: {{ .Values.externalSecrets.externalDbPort.path }}
        property: {{ .Values.externalSecrets.externalDbPort.property }}
    - secretKey: {{ .Values.externalSecrets.externalDbUser.name }}
      remoteRef:
        key: {{ .Values.externalSecrets.externalDbUser.path }}
        property: {{ .Values.externalSecrets.externalDbUser.property }}
    - secretKey: {{ .Values.externalSecrets.externalDbName.name }}
      remoteRef:
        key: {{ .Values.externalSecrets.externalDbName.path }}
        property: {{ .Values.externalSecrets.externalDbName.property }}
    - secretKey: {{ .Values.externalSecrets.externalDbRedisPort.name }}
      remoteRef:
        key: {{ .Values.externalSecrets.externalDbRedisPort.path }}
        property: {{ .Values.externalSecrets.externalDbRedisPort.property }}
    - secretKey: {{ .Values.externalSecrets.externalDbRedisHost.name }}
      remoteRef:
        key: {{ .Values.externalSecrets.externalDbRedisHost.path }}
        property: {{ .Values.externalSecrets.externalDbRedisHost.property }}

